### ISSUE TITLE
Invalid cross-device link on update config

### ISSUE THREAD

**Issue by gabfssilva** [martensson/nixy#17] opened 2016-08-12 20:42 UTC
Hi, I just upgraded my nixy version to 0.7.0 and I'm getting the following error when nixy is trying to update the config:

time="2016-08-12T17:35:49-03:00" level=error msg="unable to generate nginx config" error="rename /tmp/nixy020179483 /etc/nginx/nginx.conf: invalid cross-device link" 

Do you guys have any idea why I'm getting this error? It seems like this "/tmp/nixy020179483" file does not exist.

ps: I'm using the old template
ps2: for now I'm using the 0.6.0, as before.

**Comment by martensson** [comment] 2016-08-12 21:09
Thanks for reporting, we are now checking that the config is valid (inside a temp dir) before replacing the live version. Is /tmp and /etc mounted on different partitions? Doing some research shows this might be the cause. I will have to make a hotfix if that is the case.

In either case you might have to update your template to adapt the new changes in 0.7.0. It should only be one line if you are using the default template from 0.6.0.

**Comment by gabfssilva** [comment] 2016-08-12 22:53
Yes, the folders are mounted on different partitions, I guess that's it then: https://groups.google.com/forum/#!topic/golang-dev/5w7Jmg_iCJQ. If the answer is right, the solution is to copy and then delete the file instead of moving it.

I made a few changes with the default template in the 0.6.0 version, but, it won't be problem to adapt it again.

thanks for the quick answer!

**Comment by martensson** [comment] 2016-08-15 07:59
Fixed in https://github.com/martensson/nixy/commit/bc43747a8da47747d4bf9e383f21394d1b948d31

Making new release 0.7.1 now!

**Closed as completed by martensson** 2016-08-15 07:59 UTC
